/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package bytestring-lh-0.13.0.0 */
#ifndef VERSION_bytestring_lh
#define VERSION_bytestring_lh "0.13.0.0"
#endif /* VERSION_bytestring_lh */
#ifndef MIN_VERSION_bytestring_lh
#define MIN_VERSION_bytestring_lh(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  13 || \
  (major1) == 0 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_bytestring_lh */
/* package base-4.16.4.0 */
#ifndef VERSION_base
#define VERSION_base "4.16.4.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  16 || \
  (major1) == 4 && (major2) == 16 && (minor) <= 4)
#endif /* MIN_VERSION_base */
/* package data-array-byte-0.1.0.1 */
#ifndef VERSION_data_array_byte
#define VERSION_data_array_byte "0.1.0.1"
#endif /* VERSION_data_array_byte */
#ifndef MIN_VERSION_data_array_byte
#define MIN_VERSION_data_array_byte(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_data_array_byte */
/* package deepseq-1.4.6.1 */
#ifndef VERSION_deepseq
#define VERSION_deepseq "1.4.6.1"
#endif /* VERSION_deepseq */
#ifndef MIN_VERSION_deepseq
#define MIN_VERSION_deepseq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 6)
#endif /* MIN_VERSION_deepseq */
/* package ghc-prim-0.8.0 */
#ifndef VERSION_ghc_prim
#define VERSION_ghc_prim "0.8.0"
#endif /* VERSION_ghc_prim */
#ifndef MIN_VERSION_ghc_prim
#define MIN_VERSION_ghc_prim(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_ghc_prim */
/* package liquid-prelude-0.9.0.2 */
#ifndef VERSION_liquid_prelude
#define VERSION_liquid_prelude "0.9.0.2"
#endif /* VERSION_liquid_prelude */
#ifndef MIN_VERSION_liquid_prelude
#define MIN_VERSION_liquid_prelude(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 0)
#endif /* MIN_VERSION_liquid_prelude */
/* package liquidhaskell-0.9.2.5.0 */
#ifndef VERSION_liquidhaskell
#define VERSION_liquidhaskell "0.9.2.5.0"
#endif /* VERSION_liquidhaskell */
#ifndef MIN_VERSION_liquidhaskell
#define MIN_VERSION_liquidhaskell(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  9 || \
  (major1) == 0 && (major2) == 9 && (minor) <= 2)
#endif /* MIN_VERSION_liquidhaskell */
/* package template-haskell-2.18.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.18.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  18 || \
  (major1) == 2 && (major2) == 18 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */

/* tool gcc-15.0.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.0.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  0 || \
  (major1) == 15 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.2.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.2.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.2.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.2.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.26.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.26.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  26 || \
  (major1) == 2 && (major2) == 26 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.8 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.8"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 8)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool hscolour-1.24 */
#ifndef TOOL_VERSION_hscolour
#define TOOL_VERSION_hscolour "1.24"
#endif /* TOOL_VERSION_hscolour */
#ifndef MIN_TOOL_VERSION_hscolour
#define MIN_TOOL_VERSION_hscolour(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  24 || \
  (major1) == 1 && (major2) == 24 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hscolour */
/* tool runghc-9.2.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.2.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  2 || \
  (major1) == 9 && (major2) == 2 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "bytestring-lh-0.13.0.0-5odPtf5eoawLYRpIZ0llE6"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "bytestring-lh-0.13.0.0-5odPtf5eoawLYRpIZ0llE6"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.13.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
